# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d14c655359f6b2dd1eaac178917f62cc31f357cb88384eee311f169caf80733356490d3ec35e41ed87d7cbb86c1b716f6d6751c702698a2292e15db739938de

test:
  secret_key_base: 61b99e8d2c717c78f1890832bb3bb722400ce9e31175c3b7ec4b04b2a2aafcdb6acbb5b458b18efb16c0d8b060f3c091285f12d1dcd66394376ff1bb8a4c0e37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
